CPh.Parking.Web/Controllers/AdministrationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CPh.Parking.Web.Controllers
{
    [Authorize]
    public class AdministrationController : Controller
    {
        [Authorize(Roles = "CPh-F-ORG_HMR_Dispatch_Gcp-M,CPh-F-ORG_Itm_Pit_EngIt_Im-R")]
        public IActionResult Index()
        {
            return View();
        }
    }
}

CPh.Parking.Web/Controllers/ParkingRecordsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CPh.Parking.Web.Data;
using CPh.Parking.Web.Models;

namespace CPh.Parking.Web.Controllers
{
    public class ParkingRecordsController : Controller
    {
        private readonly ParkingDbContext _context;

        public ParkingRecordsController(ParkingDbContext context)
        {
            _context = context;
        }

        // GET: ParkingRecords
        public async Task<IActionResult> Index()
        {
            return View(await _context.ParkingRecords.ToListAsync());
        }

        // GET: ParkingRecords/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var parkingRecord = await _context.ParkingRecords
                .SingleOrDefaultAsync(m => m.Id == id);
            if (parkingRecord == null)
            {
                return NotFound();
            }

            return View(parkingRecord);
        }

        // GET: ParkingRecords/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: ParkingRecords/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,TimeIn,TimeOut")] ParkingRecord parkingRecord)
        {
            if (ModelState.IsValid)
            {
                _context.Add(parkingRecord);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(parkingRecord);
        }

        // GET: ParkingRecords/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var parkingRecord = await _context.ParkingRecords.SingleOrDefaultAsync(m => m.Id == id);
            if (parkingRecord == null)
            {
                return NotFound();
            }
            return View(parkingRecord);
        }

        // POST: ParkingRecords/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,TimeIn,TimeOut")] ParkingRecord parkingRecord)
        {
            if (id != parkingRecord.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(parkingRecord);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ParkingRecordExists(parkingRecord.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(parkingRecord);
        }

        // GET: ParkingRecords/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var parkingRecord = await _context.ParkingRecords
                .SingleOrDefaultAsync(m => m.Id == id);
            if (parkingRecord == null)
            {
                return NotFound();
            }

            return View(parkingRecord);
        }

        // POST: ParkingRecords/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var parkingRecord = await _context.ParkingRecords.SingleOrDefaultAsync(m => m.Id == id);
            _context.ParkingRecords.Remove(parkingRecord);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ParkingRecordExists(int id)
        {
            return _context.ParkingRecords.Any(e => e.Id == id);
        }
    }
}

CPh.Parking.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <title>@ViewData["Title"] - CPh.Parking.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @RenderSection("Styles", required: false)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">CPh.Parking.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
               <!-- <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li> -->
                    <li><a asp-controller="ParkingRecords" asp-action="Index">ParkingRecords</a></li>
                    <li><a asp-controller="Administration" asp-action="Index">Administrator</a></li>
                </ul>
    <p class="nav navbar-text navbar-right">Hello, Mariel Admana!</p>
    <!--  <p class="nav navbar-text navbar-right">Hello, User.FullName! </p> -->

</div>
            </div>
        </nav>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2018 - CPh.Parking.Web</p>
            </footer>
        </div>

        <environment include="Development">
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>

        @RenderSection("Scripts", required: false)
    </body>
    </html>