CPh.Parking.Web/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CPh.Parking.Web.Models
{
    public class User
    {
        [Required]
        [Display(Name = "Parking SLot No.")]
        public int Id { get; set; }

        [Required]
        [Display(Name = "Global ID")]
        public string GlobalID { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Display(Name = "First Name")]
        public string FirstName { get; set; }


        [Display(Name = "Position")]
        public string Position { get; set; }

        [Display(Name = "Hire Date")]
        [Required]
        [DataType(DataType.Date)]
        public DateTime HireDate { get; set; }

        [Display(Name = "Employee Status")]
        public Status EmpStat { get; set; }

        [Display(Name = "Current Location")]
        public string CurLoc { get; set; }

        [Display(Name = "Floor")]
        public int Floor { get; set; }

        [Display(Name = "IP Phone")]
        public string IP { get; set; }

        public virtual ICollection<Vehicle> Vehicles { get; set; }

        public enum Status
        {
            Regular,
            Probationary
        }
        
      
    }
}

CPh.Parking.Web/Models/Viewing.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CPh.Parking.Web.Models
{
    public class Viewing
    {
        
        public int Id { get; set; }

       // public virtual User User { get; set; }

        [Required]
        [Display(Name = "Global ID")]
        public string GlobalID { get; set; }

        [Required]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Display(Name = "Floor")]
        public int Floor { get; set; }

        [Display(Name = "IP Phone")]
        public string IP { get; set; }




    }
}

CPh.Parking.Web/Controllers/SampleController.cs
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using CPh.Parking.Web.Data;
using CPh.Parking.Web.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;

namespace CPh.Parking.Web.Controllers
{
    [Produces("application/json")]
    [Route("api/Sample")]
    public class SampleController : Controller
    {
        private readonly ParkingDbContext _SDB;

        public SampleController(ParkingDbContext SDB)
        {
            _SDB = SDB;
        }



        [HttpGet]
        public string Exports()
        {
            string sample = @"Sample.xlsx";
            string path = "D:\\";
            string URL = string.Format("{0}://{1}/{2}", Request.Scheme, Request.Host, sample);
            FileInfo info = new FileInfo(Path.Combine(path, sample));

            if (info.Exists)
            {
                info.Delete();
                info = new FileInfo(Path.Combine(path, sample)); 
            }
             


            using (ExcelPackage package = new ExcelPackage(info))
            {
                IList<User> users = _SDB.Users.ToList();
                ExcelWorksheet worksheet = package.Workbook.Worksheets.Add("User");
                int totalrows = users.Count();

                worksheet.Column(1).Width = 25;
                worksheet.Column(2).Width = 25;
                worksheet.Column(3).Width = 25;
                worksheet.Column(4).Width = 25;
                worksheet.Column(5).Width = 25;
                worksheet.Column(6).Width = 25;
                worksheet.Column(7).Width = 25;
                worksheet.Column(8).Width = 25;
                worksheet.Column(9).Width = 25;

                //worksheet.Column(1).alignment = 25;

                worksheet.Cells[1, 1].Value = "Global ID";
                worksheet.Cells[1, 2].Value = "Last Name;";
                worksheet.Cells[1, 3].Value = "First Name";
                worksheet.Cells[1, 4].Value = "Position";
                worksheet.Cells[1, 5].Value = "Hire Date";
                worksheet.Cells[1, 6].Value = "Employee Status";
                worksheet.Cells[1, 7].Value = "Current Location";
                worksheet.Cells[1, 8].Value = "Floor";
                worksheet.Cells[1, 9].Value = "IP Phone";

                int i = 0;
                for (int row = 2; row <= totalrows+1; row++)
                {

                    for (int m = 1; m <= 9; m++)
                    {
                        worksheet.Cells[1, m].Style.Fill.PatternType = OfficeOpenXml.Style.ExcelFillStyle.Solid;
                        worksheet.Cells[1, m].Style.Fill.BackgroundColor.SetColor(Color.LightSteelBlue);
                    }

                    worksheet.Cells[row, 1].Value = users[i].GlobalID;
                    worksheet.Cells[row, 2].Value = users[i].LastName;
                    worksheet.Cells[row, 3].Value = users[i].FirstName;
                    worksheet.Cells[row, 4].Value = users[i].Position;
                    worksheet.Cells[row, 5].Value = users[i].HireDate;
                    worksheet.Cells[row, 6].Value = users[i].EmpStat;
                    worksheet.Cells[row, 7].Value = users[i].CurLoc;
                    worksheet.Cells[row, 8].Value = users[i].Floor;
                    worksheet.Cells[row, 9].Value = users[i].IP;
                   

                    i++;
                   
                }
                
                    package.Save();
            }

            return "Saving.......";

        }
       
           


    }
}

CPh.Parking.Web/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CPh.Parking.Web.Data;
using CPh.Parking.Web.Models;

namespace CPh.Parking.Web.Controllers
{
    public class UsersController : Controller
    {
        private readonly ParkingDbContext _context;

        public UsersController(ParkingDbContext context)
        {
            _context = context;
        }

      
        //[HttpGet]
        //public async IEnumerable<User> Viewing(int? id)
        //{
        //    var user = await _context.Users.SingleOrDefaultAsync(m => m.Id == id);
        //    return 
        //}


        // GET: Users
        public async Task<IActionResult> Index()
        {
            return View(await _context.Users.ToListAsync());
        }

        
        // GET: Users/Create
        public IActionResult Create()
        {
            return View();
        }


        // POST: Users/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,GlobalID,LastName,FirstName,CCD,JG,Position,HireDate,EmpStat,CurLoc,Floor,IP")] User user)
        {
            if (ModelState.IsValid)
            {
                _context.Add(user);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users.SingleOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        // POST: Users/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,GlobalID,LastName,FirstName,CCD,JG,Position,HireDate,EmpStat,CurLoc,Floor,IP")] User user)
        {
            if (id != user.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(user);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UserExists(user.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(user);
        }

        // GET: Users/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _context.Users
                .SingleOrDefaultAsync(m => m.Id == id);
            if (user == null)
            {
                return NotFound();
            }

            return View(user);
        }

        // POST: Users/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var user = await _context.Users.SingleOrDefaultAsync(m => m.Id == id);
            _context.Users.Remove(user);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserExists(int id)
        {
            return _context.Users.Any(e => e.Id == id);
        }
    }
}

CPh.Parking.Web/Views/Users/Create.cshtml
@using CPh.Parking.Web.Models
@model CPh.Parking.Web.Models.User

@{
    ViewData["Title"] = "Create";
}

<h2>Add New</h2>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GlobalID" class="control-label"></label>
                <input asp-for="GlobalID" class="form-control" />
                <span asp-validation-for="GlobalID" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="Position" class="control-label"></label>
                <input asp-for="Position" class="form-control" />
                <span asp-validation-for="Position" class="text-danger"></span>
            </div>


            @*<div class="col-md-10">
            @Html.EditorFor(model => model.HireDate, new { htmlAttributes = new { @class = "form-control", type = "date", @Value = DateTime.Now.ToShortDateString() } })
            @Html.ValidationMessageFor(model => model.HireDate, "", new { @class = "text-danger" })
            <span class="help-block">* Mandatory Field</span>
        </div>*@


            <div class="form-group">
                <label asp-for="HireDate" class="control-label"></label>
                <input type="date" asp-for="HireDate" class="form-control" />
                <span asp-validation-for="HireDate" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="EmpStat" class="control-label"></label>
                <select asp-for="EmpStat" class="form-control" asp-items="@Html.GetEnumSelectList<CPh.Parking.Web.Models.User.Status>()"></select>
                <span asp-validation-for="EmpStat" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CurLoc" class="control-label"></label>
                <input asp-for="CurLoc" class="form-control" />
                <span asp-validation-for="CurLoc" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Floor" class="control-label"></label>
                <input asp-for="Floor" class="form-control" />
                <span asp-validation-for="Floor" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="IP" class="control-label"></label>
                <input asp-for="IP" class="form-control" />
                <span asp-validation-for="IP" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CPh.Parking.Web/Views/Users/Delete.cshtml
@model CPh.Parking.Web.Models.User

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>User</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.GlobalID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GlobalID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Position)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Position)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HireDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HireDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmpStat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmpStat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CurLoc)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CurLoc)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Floor)
        </dt>


        <dd>
            @Html.DisplayFor(model => model.Floor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IP)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CPh.Parking.Web/Views/Users/Edit.cshtml
@model CPh.Parking.Web.Models.User

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="GlobalID" class="control-label"></label>
                <input asp-for="GlobalID" class="form-control" />
                <span asp-validation-for="GlobalID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="Position" class="control-label"></label>
                <input asp-for="Position" class="form-control" />
                <span asp-validation-for="Position" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="HireDate" class="control-label"></label>
                <input asp-for="HireDate" class="form-control" />
                <span asp-validation-for="HireDate" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="EmpStat" class="control-label"></label>
                <input asp-for="EmpStat" class="form-control" />
                <span asp-validation-for="EmpStat" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="CurLoc" class="control-label"></label>
                <input asp-for="CurLoc" class="form-control" />
                <span asp-validation-for="CurLoc" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Floor" class="control-label"></label>
                <input asp-for="Floor" class="form-control" />
                <span asp-validation-for="Floor" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="IP" class="control-label"></label>
                <input asp-for="IP" class="form-control" />
                <span asp-validation-for="IP" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CPh.Parking.Web/Views/Users/Index.cshtml
@model IEnumerable<CPh.Parking.Web.Models.User>

@{
    ViewData["Title"] = "Index";
}

<h2>Users</h2>


<p>
    <a asp-action="Create">Add New</a>
    <a asp-action="Exports" asp-controller="Sample">Excel</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GlobalID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Position)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.HireDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmpStat)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CurLoc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Floor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IP)
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>

@foreach (var item in Model) {

        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GlobalID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Position)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.HireDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EmpStat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CurLoc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Floor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IP)
            </td>

            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

CPh.Parking.Web/Views/Users/Viewing.cshtml
@model CPh.Parking.Web.Models.User

<br>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.GlobalID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Floor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IP)
            </th>
            <th></th>
        </tr>
    </thead>

    <tbody>
        <tr>
            <td>
                @Html.DisplayFor(modelItem => modelItem.GlobalID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.Floor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => modelItem.IP)
            </td>
        </tr>


    </tbody>
</table>